### ISSUE TITLE
Can't get Asyncio stuff to work

### ISSUE THREAD

**Issue by LightUmbra** [bachya/pypollencom#5]
I followed your usage guide and was unable to get it to run. I used the following code.

import asyncio
from aiohttp import ClientSession
from pypollencom import Client

async def main() -> None:
    """Create the aiohttp session and run the example."""
    async with ClientSession() as websession:
        await run(websession)

async def run(websession):
    """Run."""
    client = Client('47274', websession)
    client.allergens.current()

asyncio.get_event_loop().run_until_complete(main())

I got the following error:

Pollen.py:15: RuntimeWarning: coroutine 'raise_on_invalid_zip.<locals>.decorator' was never awaited
client.allergens.current()

Also, why does this module require asyncio? It seems like overkill for this.

**Comment by bachya** [comment]
My fault on incorrect documentation. Instead of this:

```
client.allergens.current()
```

...you need to await that coroutine:

```
await client.allergens.current()
```

>Also, why does this module require asyncio? It seems like overkill for this.

asyncio is present because this library's primary purpose is use within [Home Assistant](http://home-assistant.io/) – having as many integrations as possible use asyncio helps with stability, speed, etc.
